#!/bin/bash

#Start the tree simulation with bandwidth detection

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

LOG_FILE="$DIR/explore-bw_$(date '+%m-%d_%T').txt"

#impose 10 instead of 100 originally
bw="10"
sampleSizes="5 10 25"
#detect 20Mbps difference
x="20"

randWeight="1"
ipWeight="0"
balanceWeight="0"
repeat="1 2 3 4 5 6 7 8"
global_repeat="1"
watcher="h256"

links="ls255-h256 ls253-s255 ls249-s253 ls241-s249 ls225-s241 ls193-s225 ls129-s193 ls1-s129"
topos="tree-8x2-256_bw_nobl.json"

overlay_size="256"
