#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LOG_FILE="$DIR/explore-bw_$(date '+%m-%d_%T').txt"

#impose 10 instead of 100 originally
bw="10"
sampleSizes="10 20 50"
#20 50"
bucket="probabilistic-power-bucket"
#detect 20Mbps difference
x="20"


randWeight="1"
ipWeight="0"
balanceWeight="0"
repeat="1 2 3 4 5 6 7 8"
global_repeat="1"
watcher="h512"

links="ls511-h512 ls509-s511 ls505-s509 ls497-s505 ls481-s497 ls449-s481 ls385-s449 ls257-s385 ls1-s257"
topos="$DIR/tree-9x2-512_bw_nobl.json"


overlay_size="512"
